server:
#  유레카 서버의 수신포트
  port: 8070
eureka:
  instance:
#    유레카 인스턴스의 호스트 이름
#    hostname: localhost
     hostname: eurekaserver
  client:
#    컨피그 서버가 유레카 서비스에 등록되지 않게 함
    registerWithEureka: false
#    레지스트리 정보를 로컬에 캐싱하지 않음
    fetchRegistry: false
    serviceUrl:
      defaultZone:
#       서비스 URL 제공
        http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
#    서버가 요청받기 전 초기 대기시간 설정
    waitTimeInMsWhenSyncEmpty: 30